name: excel_import_db
description: "Desktop app to import data from an Excel file into a Database."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  excel: ^4.0.6
  file_picker: ^8.1.3
  fluent_ui: ^4.9.2
  intl: ^0.19.0
  mysql1: ^0.20.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
